export type GamepadButtonType =
  | "South"
  | "East"
  | "North"
  | "West"
  | "C"
  | "Z"
  | "LeftTrigger"
  | "LeftTrigger2"
  | "RightTrigger"
  | "RightTrigger2"
  | "Select"
  | "Start"
  | "Mode"
  | "LeftThumb"
  | "RightThumb"
  | "DPadUp"
  | "DPadDown"
  | "DPadLeft"
  | "DPadRight";

export type GamepadAxisType =
  | "LeftStickX"
  | "LeftStickY"
  | "LeftZ"
  | "RightStickX"
  | "RightStickY"
  | "RightZ"
  | "DPadX"
  | "DPadY";
