/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function initOAuthClient(application: string, issuerUrl: string, clientId: string, redirectUri: string): Promise<void>
export function authenticate(scopes: Array<string>, extraParams?: Record<string, string> | undefined | null): Promise<any>
export function accessToken(): string
