/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Init the global OAuth client.
 *
 * ## Errors
 *
 * An error occurs if:
 *   - The project directory cannot be found (optional)
 *   - The OAuth client cannot be built
 *   - The global OAuth client cannot be saved
 */
export function initOAuthClient(application: string, issuerUrl: string, clientId: string, redirectUri: string): Promise<void>
/**
 * Authenticate the user.
 *
 * ## Errors
 *
 * An error occurs if:
 *   - The global OAuth client is not found
 *   - The user cannot be authenticated
 */
export function authenticate(scopes: Array<string>, extraParams?: Record<string, string> | undefined | null): Promise<any>
/**
 * Returns the current access token.
 *
 * ## Errors
 *
 * An error occurs if:
 *   - The global OAuth client is not found
 *   - The access token couldn't be read from disk
 */
export function accessToken(): string
