/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GenerateOption {
  /** Path to the _folder_ that contains all the apis definition files (.yaml), prefer absolute paths */
  path: string
  /** Name(s) of the api to generate the client code for */
  apiNames: Array<string>
  /** Output directory, prefer absolute paths */
  outDir: string
  /** Path to a Prettier config file */
  prettierConfigPath?: string
  /** Generates a full-fledged node module including a `package.json` file */
  withPackageJson?: boolean
  /** Skips code formatting */
  skipFormat?: boolean
}
/**
 * Generate api clients.
 *
 * # Errors
 *
 * Throws if the generation fails (file not found, invalid, etc...)
 */
export function generate(options: GenerateOption): void
