pub use bevy_input::keyboard::{KeyCode, KeyboardInput};

pub fn to_char(key: KeyCode) -> char {
    match key {
        KeyCode::Key1 => '1',
        KeyCode::Key2 => '2',
        KeyCode::Key3 => '3',
        KeyCode::Key4 => '4',
        KeyCode::Key5 => '5',
        KeyCode::Key6 => '6',
        KeyCode::Key7 => '7',
        KeyCode::Key8 => '8',
        KeyCode::Key9 => '9',
        KeyCode::Key0 => '0',

        KeyCode::A => 'a',
        KeyCode::B => 'b',
        KeyCode::C => 'c',
        KeyCode::D => 'd',
        KeyCode::E => 'e',
        KeyCode::F => 'f',
        KeyCode::G => 'g',
        KeyCode::H => 'h',
        KeyCode::I => 'i',
        KeyCode::J => 'j',
        KeyCode::K => 'k',
        KeyCode::L => 'l',
        KeyCode::M => 'm',
        KeyCode::N => 'n',
        KeyCode::O => 'o',
        KeyCode::P => 'p',
        KeyCode::Q => 'q',
        KeyCode::R => 'r',
        KeyCode::S => 's',
        KeyCode::T => 't',
        KeyCode::U => 'u',
        KeyCode::V => 'v',
        KeyCode::W => 'w',
        KeyCode::X => 'x',
        KeyCode::Y => 'y',
        KeyCode::Z => 'z',

        //Escape,

        //F1,
        //F2,
        //F3,
        //F4,
        //F5,
        //F6,
        //F7,
        //F8,
        //F9,
        //F10,
        //F11,
        //F12,
        //F13,
        //F14,
        //F15,
        //F16,
        //F17,
        //F18,
        //F19,
        //F20,
        //F21,
        //F22,
        //F23,
        //F24,

        //Snapshot,
        //Scroll,
        //Pause,

        //Insert,
        //Home,
        //Delete,
        //End,
        //PageDown,
        //PageUp,

        //Left,
        //Up,
        //Right,
        //Down,

        //Back,
        //Return,
        KeyCode::Space => ' ',

        //Compose,

        //Caret,

        //Numlock,
        //Numpad0,
        //Numpad1,
        //Numpad2,
        //Numpad3,
        //Numpad4,
        //Numpad5,
        //Numpad6,
        //Numpad7,
        //Numpad8,
        //Numpad9,

        //AbntC1,
        //AbntC2,
        //NumpadAdd,
        KeyCode::Apostrophe => '\'',
        //Apps,
        KeyCode::Asterisk => '*',
        KeyCode::Plus => '+',
        KeyCode::At => '@',
        //Ax,
        KeyCode::Backslash => '\\',
        //Calculator,
        //KeyCode::Capital => '',
        KeyCode::Colon => ':',
        KeyCode::Comma => ',',
        //KeyCode::Convert => '',
        //KeyCode::NumpadDecimal => '',
        //KeyCode::NumpadDivide => '',
        KeyCode::Equals => '=',
        KeyCode::Grave => '`',
        //KeyCode::Kana => '',
        //KeyCode::Kanji => '',
        //KeyCode::LAlt => '',
        //KeyCode::LBracket => '(',
        //KeyCode::LControl => '',
        //KeyCode::LShift => '',
        //KeyCode::LWin => '',
        //KeyCode::Mail => '',
        //KeyCode::MediaSelect => '',
        //KeyCode::MediaStop => '',
        KeyCode::Minus => '-',
        //KeyCode::NumpadMultiply => '',
        //KeyCode::Mute => '',
        //KeyCode::MyComputer => '',
        //KeyCode::NavigateForward => '',  // also called "Prior"
        //KeyCode::NavigateBackward => '', // also called "Next"
        //KeyCode::NextTrack => '',
        //KeyCode::NoConvert => '',
        //KeyCode::NumpadComma => '',
        //KeyCode::NumpadEnter => '',
        //KeyCode::NumpadEquals => '',
        //KeyCode::Oem102 => '',
        KeyCode::Period => '.',
        //KeyCode::PlayPause => '',
        //KeyCode::Power => '',
        //KeyCode::PrevTrack => '',
        //KeyCode::RAlt => '',
        KeyCode::RBracket => ')',
        //KeyCode::RControl => '',
        //KeyCode::RShift => '',
        //KeyCode::RWin => '',
        KeyCode::Semicolon => ';',
        KeyCode::Slash => '/',
        //KeyCode::Sleep => '',
        //KeyCode::Stop => '',
        //KeyCode::NumpadSubtract => '',
        //KeyCode::Sysrq => '',
        //KeyCode::Tab => '',
        KeyCode::Underline => '_',
        //KeyCode::Unlabeled => '',
        //KeyCode::VolumeDown => '',
        //KeyCode::VolumeUp => '',
        //KeyCode::Wake => '',
        //KeyCode::WebBack => '',
        //KeyCode::WebFavorites => '',
        //KeyCode::WebForward => '',
        //KeyCode::WebHome => '',
        //KeyCode::WebRefresh => '',
        //KeyCode::WebSearch => '',
        //KeyCode::WebStop => '',
        //KeyCode::Yen => '',
        //KeyCode::Copy => '',
        //KeyCode::Paste => '',
        //KeyCode::Cut => '',
        _ => 0 as char,
    }
}
