use legion_input::{
    keyboard::{KeyCode, KeyboardInput},
    mouse::MouseButton,
    touch::{ForceTouch, TouchInput, TouchPhase},
    ElementState,
};
use legion_math::Vec2;

pub fn convert_keyboard_input(keyboard_input: &tao::event::KeyEvent) -> KeyboardInput {
    KeyboardInput {
        scan_code: keyboard_input.physical_key.to_scancode().unwrap_or(0),
        state: convert_element_state(keyboard_input.state),
        key_code: convert_physical_key_code(keyboard_input.physical_key),
    }
}

pub fn convert_element_state(element_state: tao::event::ElementState) -> ElementState {
    match element_state {
        tao::event::ElementState::Pressed => ElementState::Pressed,
        tao::event::ElementState::Released => ElementState::Released,
        _ => panic!(),
    }
}

pub fn convert_mouse_button(mouse_button: tao::event::MouseButton) -> MouseButton {
    match mouse_button {
        tao::event::MouseButton::Left => MouseButton::Left,
        tao::event::MouseButton::Right => MouseButton::Right,
        tao::event::MouseButton::Middle => MouseButton::Middle,
        tao::event::MouseButton::Other(val) => MouseButton::Other(val),
        _ => panic!(),
    }
}

pub fn convert_touch_input(
    touch_input: tao::event::Touch,
    location: tao::dpi::LogicalPosition<f32>,
) -> TouchInput {
    TouchInput {
        phase: match touch_input.phase {
            tao::event::TouchPhase::Started => TouchPhase::Started,
            tao::event::TouchPhase::Moved => TouchPhase::Moved,
            tao::event::TouchPhase::Ended => TouchPhase::Ended,
            tao::event::TouchPhase::Cancelled => TouchPhase::Cancelled,
            _ => panic!(),
        },
        position: Vec2::new(location.x as f32, location.y as f32),
        force: touch_input.force.map(|f| match f {
            tao::event::Force::Calibrated {
                force,
                max_possible_force,
                altitude_angle,
                ..
            } => ForceTouch::Calibrated {
                force,
                max_possible_force,
                altitude_angle,
            },
            tao::event::Force::Normalized(x) => ForceTouch::Normalized(x),
            _ => panic!(),
        }),
        id: touch_input.id,
    }
}

pub fn convert_physical_key_code(key_code: tao::keyboard::KeyCode) -> Option<KeyCode> {
    match key_code {
        tao::keyboard::KeyCode::Digit1 => Some(KeyCode::Key1),
        tao::keyboard::KeyCode::Digit2 => Some(KeyCode::Key2),
        tao::keyboard::KeyCode::Digit3 => Some(KeyCode::Key3),
        tao::keyboard::KeyCode::Digit4 => Some(KeyCode::Key4),
        tao::keyboard::KeyCode::Digit5 => Some(KeyCode::Key5),
        tao::keyboard::KeyCode::Digit6 => Some(KeyCode::Key6),
        tao::keyboard::KeyCode::Digit7 => Some(KeyCode::Key7),
        tao::keyboard::KeyCode::Digit8 => Some(KeyCode::Key8),
        tao::keyboard::KeyCode::Digit9 => Some(KeyCode::Key9),
        tao::keyboard::KeyCode::Digit0 => Some(KeyCode::Key0),
        tao::keyboard::KeyCode::KeyA => Some(KeyCode::A),
        tao::keyboard::KeyCode::KeyB => Some(KeyCode::B),
        tao::keyboard::KeyCode::KeyC => Some(KeyCode::C),
        tao::keyboard::KeyCode::KeyD => Some(KeyCode::D),
        tao::keyboard::KeyCode::KeyE => Some(KeyCode::E),
        tao::keyboard::KeyCode::KeyF => Some(KeyCode::F),
        tao::keyboard::KeyCode::KeyG => Some(KeyCode::G),
        tao::keyboard::KeyCode::KeyH => Some(KeyCode::H),
        tao::keyboard::KeyCode::KeyI => Some(KeyCode::I),
        tao::keyboard::KeyCode::KeyJ => Some(KeyCode::J),
        tao::keyboard::KeyCode::KeyK => Some(KeyCode::K),
        tao::keyboard::KeyCode::KeyL => Some(KeyCode::L),
        tao::keyboard::KeyCode::KeyM => Some(KeyCode::M),
        tao::keyboard::KeyCode::KeyN => Some(KeyCode::N),
        tao::keyboard::KeyCode::KeyO => Some(KeyCode::O),
        tao::keyboard::KeyCode::KeyP => Some(KeyCode::P),
        tao::keyboard::KeyCode::KeyQ => Some(KeyCode::Q),
        tao::keyboard::KeyCode::KeyR => Some(KeyCode::R),
        tao::keyboard::KeyCode::KeyS => Some(KeyCode::S),
        tao::keyboard::KeyCode::KeyT => Some(KeyCode::T),
        tao::keyboard::KeyCode::KeyU => Some(KeyCode::U),
        tao::keyboard::KeyCode::KeyV => Some(KeyCode::V),
        tao::keyboard::KeyCode::KeyW => Some(KeyCode::W),
        tao::keyboard::KeyCode::KeyX => Some(KeyCode::X),
        tao::keyboard::KeyCode::KeyY => Some(KeyCode::Y),
        tao::keyboard::KeyCode::KeyZ => Some(KeyCode::Z),
        tao::keyboard::KeyCode::Escape => Some(KeyCode::Escape),
        tao::keyboard::KeyCode::F1 => Some(KeyCode::F1),
        tao::keyboard::KeyCode::F2 => Some(KeyCode::F2),
        tao::keyboard::KeyCode::F3 => Some(KeyCode::F3),
        tao::keyboard::KeyCode::F4 => Some(KeyCode::F4),
        tao::keyboard::KeyCode::F5 => Some(KeyCode::F5),
        tao::keyboard::KeyCode::F6 => Some(KeyCode::F6),
        tao::keyboard::KeyCode::F7 => Some(KeyCode::F7),
        tao::keyboard::KeyCode::F8 => Some(KeyCode::F8),
        tao::keyboard::KeyCode::F9 => Some(KeyCode::F9),
        tao::keyboard::KeyCode::F10 => Some(KeyCode::F10),
        tao::keyboard::KeyCode::F11 => Some(KeyCode::F11),
        tao::keyboard::KeyCode::F12 => Some(KeyCode::F12),
        tao::keyboard::KeyCode::F13 => Some(KeyCode::F13),
        tao::keyboard::KeyCode::F14 => Some(KeyCode::F14),
        tao::keyboard::KeyCode::F15 => Some(KeyCode::F15),
        tao::keyboard::KeyCode::F16 => Some(KeyCode::F16),
        tao::keyboard::KeyCode::F17 => Some(KeyCode::F17),
        tao::keyboard::KeyCode::F18 => Some(KeyCode::F18),
        tao::keyboard::KeyCode::F19 => Some(KeyCode::F19),
        tao::keyboard::KeyCode::F20 => Some(KeyCode::F20),
        tao::keyboard::KeyCode::F21 => Some(KeyCode::F21),
        tao::keyboard::KeyCode::F22 => Some(KeyCode::F22),
        tao::keyboard::KeyCode::F23 => Some(KeyCode::F23),
        tao::keyboard::KeyCode::F24 => Some(KeyCode::F24),
        tao::keyboard::KeyCode::F25 => todo!(),
        tao::keyboard::KeyCode::F26 => todo!(),
        tao::keyboard::KeyCode::F27 => todo!(),
        tao::keyboard::KeyCode::F28 => todo!(),
        tao::keyboard::KeyCode::F29 => todo!(),
        tao::keyboard::KeyCode::F30 => todo!(),
        tao::keyboard::KeyCode::F31 => todo!(),
        tao::keyboard::KeyCode::F32 => todo!(),
        tao::keyboard::KeyCode::F33 => todo!(),
        tao::keyboard::KeyCode::F34 => todo!(),
        tao::keyboard::KeyCode::F35 => todo!(),
        tao::keyboard::KeyCode::ScrollLock => Some(KeyCode::Scroll),
        tao::keyboard::KeyCode::Pause => Some(KeyCode::Pause),
        tao::keyboard::KeyCode::Insert => Some(KeyCode::Insert),
        tao::keyboard::KeyCode::Home => Some(KeyCode::Home),
        tao::keyboard::KeyCode::Delete => Some(KeyCode::Delete),
        tao::keyboard::KeyCode::End => Some(KeyCode::End),
        tao::keyboard::KeyCode::PageDown => Some(KeyCode::PageDown),
        tao::keyboard::KeyCode::PageUp => Some(KeyCode::PageUp),
        tao::keyboard::KeyCode::ArrowLeft => Some(KeyCode::Left),
        tao::keyboard::KeyCode::ArrowUp => Some(KeyCode::Up),
        tao::keyboard::KeyCode::ArrowRight => Some(KeyCode::Right),
        tao::keyboard::KeyCode::ArrowDown => Some(KeyCode::Down),
        tao::keyboard::KeyCode::Backspace => Some(KeyCode::Back),
        tao::keyboard::KeyCode::Enter => Some(KeyCode::Return),
        tao::keyboard::KeyCode::Space => Some(KeyCode::Space),
        tao::keyboard::KeyCode::NumLock => Some(KeyCode::Numlock),
        tao::keyboard::KeyCode::Numpad0 => Some(KeyCode::Numpad0),
        tao::keyboard::KeyCode::Numpad1 => Some(KeyCode::Numpad1),
        tao::keyboard::KeyCode::Numpad2 => Some(KeyCode::Numpad2),
        tao::keyboard::KeyCode::Numpad3 => Some(KeyCode::Numpad3),
        tao::keyboard::KeyCode::Numpad4 => Some(KeyCode::Numpad4),
        tao::keyboard::KeyCode::Numpad5 => Some(KeyCode::Numpad5),
        tao::keyboard::KeyCode::Numpad6 => Some(KeyCode::Numpad6),
        tao::keyboard::KeyCode::Numpad7 => Some(KeyCode::Numpad7),
        tao::keyboard::KeyCode::Numpad8 => Some(KeyCode::Numpad8),
        tao::keyboard::KeyCode::Numpad9 => Some(KeyCode::Numpad9),
        tao::keyboard::KeyCode::NumpadAdd => Some(KeyCode::NumpadAdd),
        tao::keyboard::KeyCode::Backslash => Some(KeyCode::Backslash),
        tao::keyboard::KeyCode::Comma => Some(KeyCode::Comma),
        tao::keyboard::KeyCode::Convert => Some(KeyCode::Convert),
        tao::keyboard::KeyCode::NumpadDecimal => Some(KeyCode::NumpadDecimal),
        tao::keyboard::KeyCode::NumpadDivide => Some(KeyCode::NumpadDivide),
        tao::keyboard::KeyCode::Equal => Some(KeyCode::Equals),
        tao::keyboard::KeyCode::MediaSelect => Some(KeyCode::MediaSelect),
        tao::keyboard::KeyCode::MediaStop => Some(KeyCode::MediaStop),
        tao::keyboard::KeyCode::Minus => Some(KeyCode::Minus),
        tao::keyboard::KeyCode::NumpadMultiply => Some(KeyCode::NumpadMultiply),
        tao::keyboard::KeyCode::NumpadComma => Some(KeyCode::NumpadComma),
        tao::keyboard::KeyCode::NumpadEnter => Some(KeyCode::NumpadEnter),
        tao::keyboard::KeyCode::NumpadEqual => Some(KeyCode::NumpadEquals),
        tao::keyboard::KeyCode::Period => Some(KeyCode::Period),
        tao::keyboard::KeyCode::Power => Some(KeyCode::Power),
        tao::keyboard::KeyCode::Semicolon => Some(KeyCode::Semicolon),
        tao::keyboard::KeyCode::Slash => Some(KeyCode::Slash),
        tao::keyboard::KeyCode::Sleep => Some(KeyCode::Sleep),
        tao::keyboard::KeyCode::NumpadSubtract => Some(KeyCode::NumpadSubtract),
        tao::keyboard::KeyCode::Tab => Some(KeyCode::Tab),
        tao::keyboard::KeyCode::AudioVolumeDown => Some(KeyCode::VolumeDown),
        tao::keyboard::KeyCode::AudioVolumeMute => Some(KeyCode::Mute),
        tao::keyboard::KeyCode::AudioVolumeUp => Some(KeyCode::VolumeUp),
        tao::keyboard::KeyCode::Copy => Some(KeyCode::Copy),
        tao::keyboard::KeyCode::Paste => Some(KeyCode::Paste),
        tao::keyboard::KeyCode::Cut => Some(KeyCode::Cut),
        tao::keyboard::KeyCode::AltLeft => Some(KeyCode::LAlt),
        tao::keyboard::KeyCode::AltRight => Some(KeyCode::RAlt),
        tao::keyboard::KeyCode::CapsLock => Some(KeyCode::Capital),
        tao::keyboard::KeyCode::ControlLeft => Some(KeyCode::LControl),
        tao::keyboard::KeyCode::ControlRight => Some(KeyCode::RControl),
        tao::keyboard::KeyCode::ShiftLeft => Some(KeyCode::LShift),
        tao::keyboard::KeyCode::ShiftRight => Some(KeyCode::RShift),
        tao::keyboard::KeyCode::IntlYen => Some(KeyCode::Yen),
        tao::keyboard::KeyCode::PrintScreen => Some(KeyCode::Snapshot),
        //tao::keyboard::KeyCode::IntlRo => todo!(),
        //tao::keyboard::KeyCode::Quote => todo!(),
        //tao::keyboard::KeyCode::ContextMenu => todo!(),
        //tao::keyboard::KeyCode::Backquote => todo!(),
        //tao::keyboard::KeyCode::BracketLeft => todo!(),
        //tao::keyboard::KeyCode::BracketRight => todo!(),
        //tao::keyboard::KeyCode::IntlBackslash => todo!(),
        //tao::keyboard::KeyCode::SuperLeft => todo!(),
        //tao::keyboard::KeyCode::SuperRight => todo!(),
        //tao::keyboard::KeyCode::KanaMode => todo!(),
        //tao::keyboard::KeyCode::Lang1 => todo!(),
        //tao::keyboard::KeyCode::Lang2 => todo!(),
        //tao::keyboard::KeyCode::Lang3 => todo!(),
        //tao::keyboard::KeyCode::Lang4 => todo!(),
        //tao::keyboard::KeyCode::Lang5 => todo!(),
        //tao::keyboard::KeyCode::NonConvert => todo!(),
        //tao::keyboard::KeyCode::Help => todo!(),
        //tao::keyboard::KeyCode::NumpadBackspace => todo!(),
        //tao::keyboard::KeyCode::NumpadClear => todo!(),
        //tao::keyboard::KeyCode::NumpadClearEntry => todo!(),
        //tao::keyboard::KeyCode::NumpadHash => todo!(),
        //tao::keyboard::KeyCode::NumpadMemoryAdd => todo!(),
        //tao::keyboard::KeyCode::NumpadMemoryClear => todo!(),
        //tao::keyboard::KeyCode::NumpadMemoryRecall => todo!(),
        //tao::keyboard::KeyCode::NumpadMemoryStore => todo!(),
        //tao::keyboard::KeyCode::NumpadMemorySubtract => todo!(),
        //tao::keyboard::KeyCode::NumpadParenLeft => todo!(),
        //tao::keyboard::KeyCode::NumpadParenRight => todo!(),
        //tao::keyboard::KeyCode::NumpadStar => todo!(),
        //tao::keyboard::KeyCode::Fn => todo!(),
        //tao::keyboard::KeyCode::FnLock => todo!(),
        //tao::keyboard::KeyCode::BrowserBack => todo!(),
        //tao::keyboard::KeyCode::BrowserFavorites => todo!(),
        //tao::keyboard::KeyCode::BrowserForward => todo!(),
        //tao::keyboard::KeyCode::BrowserHome => todo!(),
        //tao::keyboard::KeyCode::BrowserRefresh => todo!(),
        //tao::keyboard::KeyCode::BrowserSearch => todo!(),
        //tao::keyboard::KeyCode::BrowserStop => todo!(),
        //tao::keyboard::KeyCode::Eject => todo!(),
        //tao::keyboard::KeyCode::LaunchApp1 => todo!(),
        //tao::keyboard::KeyCode::LaunchApp2 => todo!(),
        //tao::keyboard::KeyCode::LaunchMail => todo!(),
        //tao::keyboard::KeyCode::MediaPlayPause => todo!(),
        //tao::keyboard::KeyCode::MediaTrackNext => todo!(),
        //tao::keyboard::KeyCode::MediaTrackPrevious => todo!(),
        //tao::keyboard::KeyCode::WakeUp => todo!(),
        //tao::keyboard::KeyCode::Hyper => todo!(),
        //tao::keyboard::KeyCode::Turbo => todo!(),
        //tao::keyboard::KeyCode::Abort => todo!(),
        //tao::keyboard::KeyCode::Resume => todo!(),
        //tao::keyboard::KeyCode::Suspend => todo!(),
        //tao::keyboard::KeyCode::Again => todo!(),
        //tao::keyboard::KeyCode::Find => todo!(),
        //tao::keyboard::KeyCode::Open => todo!(),
        //tao::keyboard::KeyCode::Props => todo!(),
        //tao::keyboard::KeyCode::Select => todo!(),
        //tao::keyboard::KeyCode::Undo => todo!(),
        //tao::keyboard::KeyCode::Hiragana => todo!(),
        //tao::keyboard::KeyCode::Katakana => todo!(),
        _ => None,
    }
}
