// source: process.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.telemetry.Process', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.telemetry.Process = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.telemetry.Process, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.telemetry.Process.displayName = 'proto.telemetry.Process';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.telemetry.Process.prototype.toObject = function(opt_includeInstance) {
  return proto.telemetry.Process.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.telemetry.Process} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.telemetry.Process.toObject = function(includeInstance, msg) {
  var f, obj = {
    processId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    exe: jspb.Message.getFieldWithDefault(msg, 2, ""),
    username: jspb.Message.getFieldWithDefault(msg, 3, ""),
    realname: jspb.Message.getFieldWithDefault(msg, 4, ""),
    computer: jspb.Message.getFieldWithDefault(msg, 5, ""),
    distro: jspb.Message.getFieldWithDefault(msg, 6, ""),
    cpuBrand: jspb.Message.getFieldWithDefault(msg, 7, ""),
    tscFrequency: jspb.Message.getFieldWithDefault(msg, 8, 0),
    startTime: jspb.Message.getFieldWithDefault(msg, 9, ""),
    startTicks: jspb.Message.getFieldWithDefault(msg, 10, 0),
    parentProcessId: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.telemetry.Process}
 */
proto.telemetry.Process.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.telemetry.Process;
  return proto.telemetry.Process.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.telemetry.Process} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.telemetry.Process}
 */
proto.telemetry.Process.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProcessId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExe(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRealname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setComputer(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDistro(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpuBrand(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTscFrequency(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartTime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStartTicks(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentProcessId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.telemetry.Process.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.telemetry.Process.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.telemetry.Process} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.telemetry.Process.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProcessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExe();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRealname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getComputer();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDistro();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCpuBrand();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTscFrequency();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getStartTime();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getStartTicks();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getParentProcessId();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string process_id = 1;
 * @return {string}
 */
proto.telemetry.Process.prototype.getProcessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setProcessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string exe = 2;
 * @return {string}
 */
proto.telemetry.Process.prototype.getExe = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setExe = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string username = 3;
 * @return {string}
 */
proto.telemetry.Process.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string realname = 4;
 * @return {string}
 */
proto.telemetry.Process.prototype.getRealname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setRealname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string computer = 5;
 * @return {string}
 */
proto.telemetry.Process.prototype.getComputer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setComputer = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string distro = 6;
 * @return {string}
 */
proto.telemetry.Process.prototype.getDistro = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setDistro = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string cpu_brand = 7;
 * @return {string}
 */
proto.telemetry.Process.prototype.getCpuBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setCpuBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint64 tsc_frequency = 8;
 * @return {number}
 */
proto.telemetry.Process.prototype.getTscFrequency = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setTscFrequency = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string start_time = 9;
 * @return {string}
 */
proto.telemetry.Process.prototype.getStartTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setStartTime = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional uint64 start_ticks = 10;
 * @return {number}
 */
proto.telemetry.Process.prototype.getStartTicks = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setStartTicks = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string parent_process_id = 11;
 * @return {string}
 */
proto.telemetry.Process.prototype.getParentProcessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.telemetry.Process} returns this
 */
proto.telemetry.Process.prototype.setParentProcessId = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


goog.object.extend(exports, proto.telemetry);
